feat(ansible): add better logging when installing dotfiles

diff --git a/bin/dotfiles b/bin/dotfiles
--- a/bin/dotfiles
+++ b/bin/dotfiles
@@ -3,20 +3,32 @@ set -e
 export GITHUB_USERNAME="Younes-Nait-Bakkou"
 DOTFILES_DIR="$HOME/.dotfiles"
 LOG_FILE="$HOME/.dotfiles-install.log"
+ERROR_LOG_FILE="$HOME/.dotfiles-install.err"
+
+# --- COLORS (for prettier terminal output) ---
+RED="\033[31m"
+GREEN="\033[32m"
+RESET="\033[0m"
 
 _log() {
-    echo "[INFO] $1"
+    local msg="$1"
+    echo -e "${GREEN}[INFO]${RESET} $msg"
+    echo "$(date '+%Y-%m-%d %H:%M:%S') [INFO] $msg" >>"$LOG_FILE"
 }
 
 _error() {
-    echo "[ERROR] $1" >&2
+    local msg="$1"
+    echo -e "${RED}[ERROR]${RESET} $msg" >&2
+    echo "$(date '+%Y-%m-%d %H:%M:%S') [ERROR] $msg" >>"$LOG_FILE"
     exit 1
 }
 
 _cmd() {
-    "$@" >>"$LOG_FILE" 2>&1 || _error "Command failed: $*"
-}
+    echo "$(date '+%Y-%m-%d %H:%M:%S') [CMD] $*" >>"$LOG_FILE"
 
+    "$@" >>"$LOG_FILE" 2>&1 ||
+        _error "Command failed: $*"
+}
 detect_os() {
     if [ -f /etc/os-release ]; then
         . /etc/os-release
