remove OPENAI_API_KEY, add JAVA_HOME env variable  and django alias

diff --git a/dot_zshrc b/dot_zshrc
--- a/dot_zshrc
+++ b/dot_zshrc
@@ -4,6 +4,7 @@
 if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
   source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
 fi
+export EDITOR="nvim"
 
 # If you come from bash you might have to change your $PATH.
 export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH
@@ -11,9 +12,6 @@ export PATH=$PATH:/opt/nvim-linux64/bin
 
 # Path to your Oh My Zsh installation.
 export ZSH="$HOME/.oh-my-zsh"
-
-# Environment Variables 
-export OPENAI_API_KEY="[REDACTED]"
 
 # Set name of the theme to load --- if set to "random", it will
 # load a random theme each time Oh My Zsh is loaded, in which case,
@@ -130,3 +128,50 @@ export NVM_DIR="$HOME/.nvm"
 [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
 
 
+# export PATH="$HOME/miniconda3/bin:$PATH"  # commented out by conda initialize
+
+# >>> conda initialize >>>
+# !! Contents within this block are managed by 'conda init' !!
+__conda_setup="$('/home/younes/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
+if [ $? -eq 0 ]; then
+    eval "$__conda_setup"
+else
+    if [ -f "/home/younes/miniconda3/etc/profile.d/conda.sh" ]; then
+        . "/home/younes/miniconda3/etc/profile.d/conda.sh"
+    else
+        export PATH="/home/younes/miniconda3/bin:$PATH"
+    fi
+fi
+unset __conda_setup
+# <<< conda initialize <<<
+#
+export PATH="$HOME/.local/bin:$PATH"
+export PATH="$PATH:/opt/nvim-linux64/bin"
+export LD_LIBRARY_PATH="/usr/lib/x86_64-linux-gnu/libmysqlclient.so.21.2.39:/usr/lib/x86_64-linux-gnu/libmysqlclient.so:/usr/lib/x86_64-linux-gnu/libmysqlclient.so.21:$LD_LIBRARY_PATH"
+
+export CFLAGS="-I/usr/include/mysql"
+export LDFLAGS="-L/usr/lib/x86_64-linux-gnu"
+
+# Check if `java --version` is successful
+if java --version > /dev/null 2>&1; then
+    # echo "Java is installed."
+
+    # Find the Java executable path
+    JAVA_PATH=$(readlink -f $(which java))
+
+    # Derive JAVA_HOME by going up two levels from the Java binary
+    JAVA_HOME=$(dirname $(dirname $JAVA_PATH))
+
+    # Export JAVA_HOME and update PATH
+    export JAVA_HOME
+    export PATH=$JAVA_HOME/bin:$PATH
+
+    # echo "JAVA_HOME is set to: $JAVA_HOME"
+else
+    echo "Java is not installed or not found in PATH."
+fi
+
+# eval $(ssh-agent -s)
+# ssh-add ~/.ssh/id_ed25519
+
+alias django="python manage.py"
